name: Selective Job Execution via Environment

on:
  push:
    branches: [ main ]

env:
  MESSAGE: "Hello from the selected job!"

jobs:
  job-a:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job A
        run: echo "$MESSAGE - Job A was executed!"
    # This job will only run if approved via the environment

  job-b:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job B
        run: echo "$MESSAGE - Job B was executed!"
    # This job will only run if approved via the environment

  job-c:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job C
        run: echo "$MESSAGE - Job C was executed!"
    # This job will only run if approved via the environment