name: Selective Job Approval via GUI

on:
  push

env:
  MESSAGE: "Hello from the selected job!"

jobs:
  job-a:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job A
        run: echo "$MESSAGE - Job A was approved and executed!"

  job-b:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job B
        run: echo "$MESSAGE - Job B was approved and executed!"

  job-c:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Print message from Job C
        run: echo "$MESSAGE - Job C was approved and executed!"