name: Single Environment Selective Job Workflow

on:
  push:
    branches:
      - main  
    
      
jobs:
  approval:
    name: Job Selection
    runs-on: ubuntu-latest
    environment: Testing 
    outputs:
      selected_job: ${{ steps.job_selector.outputs.selected_job }}
    steps:
      - name: Select job to run
        id: job_selector
        run: |
          selected_job="${{ vars.SELECTED_JOB }}"
          
          if [[ -z "$selected_job" ]]; then
            # Default if no selection is made
            selected_job="NONE"
          fi
          
          echo "selected_job=$selected_job" >> $GITHUB_OUTPUT
          echo "Selected job to run: $selected_job"

  job_A:
    name: Job A
    needs: approval
    if: needs.approval.outputs.selected_job == 'A'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Job A
        run: echo "Hello World from Job A!"

  job_B:
    name: Job B
    needs: approval
    if: needs.approval.outputs.selected_job == 'B'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Job B
        run: echo "Hello World from Job B!"

  job_C:
    name: Job C
    needs: approval
    if: needs.approval.outputs.selected_job == 'C'
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Job C
        run: echo "Hello World from Job C!"