name: Simple Job Selection Workflow

on:
  push:
    branches:
      - main

jobs:
  approval:
    name: Job Selection
    runs-on: ubuntu-latest
    environment: Testing  
    outputs:
      job: ${{ steps.select.outputs.selected_job }}
    steps:
      - id: select
        run: echo "selected_job=${{ vars.JOB }}" >> $GITHUB_OUTPUT

  run_jobs:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Job A
        if: needs.approval.outputs.job == 'A'
        run: echo "Hello World from Job A!"
        
      - name: Job B
        if: needs.approval.outputs.job == 'B'
        run: echo "Hello World from Job B!"
        
      - name: Job C
        if: needs.approval.outputs.job == 'C'
        run: echo "Hello World from Job C!"